name: Build and publish GitHub pages

on:
  push:
    branches:
      - main

jobs:
  pdoc:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install pdoc
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc
          python -m pip install -r requirements.txt
          python -m pip install -r requirements.dev.txt

      - name: Version fix
        run: |
          pip3 uninstall -y pycuda
          pip3 install numpy==1.19.4
          pip3 install pycuda==2019.1

      - name: Run pdoc
        run: pdoc -o docs turbo_broccoli

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
